### ISSUE TITLE
Warning message with Homebridge 1.1.1

### ISSUE THREAD

**Issue by vdrover** [colinbendell/homebridge-blink-for-home#13]
I was testing Homebridge 1.1.1 with blink 5.3.13 and 5.3.14 and received this warning: 

```
The plugin "homebridge-blink-for-home" requires a Homebridge version of >=1.2.0 which does not satisfy the current Homebridge version of 1.1.1. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
```

Everything seems to be working fine otherwise. 

BTW, where can someone buy you a coffee!

**Comment by colinbendell** [comment]
> The plugin "homebridge-blink-for-home" requires a Homebridge version of >=1.2.0 which does not satisfy the current Homebridge version of 1.1.1. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

I think Homebridge [1.2.3](https://github.com/homebridge/homebridge/releases) is the latest. Maybe upgrade your homebridge?

> Everything seems to be working fine otherwise.

Awesome! glad to hear!

> BTW, where can someone buy you a coffee!

I'd rather a pay-it-forward kind of appreciation. Make a donation to your local foodbank, girls who code or other local STEM program and I'll add you to a list of supporters.

**Comment by colinbendell** [comment]
This is a HOOBs issue. Contact them to upgrade the core homebridge
