### ISSUE TITLE
Flagged by Blink's Technical Support

### ISSUE THREAD

**Issue by ratsoid** [colinbendell/homebridge-blink-for-home#15]
So then this happened:

` My name is _______ and I am with the Blink team. While doing a routine server audit, your account was flagged and subsequently disabled due to unsupported scripts or apps running on your system. The only automation that is permitted for use with the Blink system is through Alexa and/or IFTTT. Please disable these scripts or apps and reach back out to me so that I can re-enable your account. `

I removed the code from my config.json for the time being. Be warned that you might be _audited_ next.

**Comment by monteroman** [comment]
I had the same thing happen. 
:This makes me super sad.

**Comment by colinbendell** [comment]
Can you PM me the contact at Blink that sent the audit?

**Comment by monteroman** [comment]
sent to your email...

**Comment by colinbendell** [comment]
I've added another optimization for the thumbnail aPI. It was polling periodically even if the home app wasn't needing it. This should substantially reduce the thumbnail api requests and put you under the radar again.

If you want to re-enable, I would be sure to change the 'name' field in the settings. By default it is 'Blink' which is used with your email to generate a UUID. Changing this name will make the app appear like a new client.

**Comment by ratsoid** [comment]
Nice, will report if something new comes up.

**Comment by tombenton55** [comment]
This happened to me when i used the other blink plugin that someone had developed.
Although, they werent as polite as the admin email you got. I had to make several phone calls to get my account reinstated.

**Comment by colinbendell** [comment]
As mentioned in #22: 
> I did a bunch of packet inspections of the app and changed the fingerprinting to mirror exactly the behaviour of the app. There is a little bit more to do, but generally we should be a lot harder to distinguish this app. It's a bit cat and mouse. I've reached out to Lab126 to see if we can get official blessing.

Closing this issue for now.
