### ISSUE TITLE
Notifications app Home Apple Homekit?

### ISSUE THREAD

**Issue by sentocv** [colinbendell/homebridge-blink-for-home#23]
When any camera detects motion, dont show notification app Home Apple, only app Blink. 

Its correct? Ant possibility to recieve notifications app home Apple? 

Thanks!

**Comment by colinbendell** [comment]
You need to enable the notifications on the camera. I think notifications are disabled by default

**Comment by sentocv** [comment]
Thanks for the fast reply!

The notifications with your plugin... are the same that a camera homekit compatible(native) ?

**Comment by colinbendell** [comment]
It is under home settings > camera. You can set the notifications up there.

**Comment by sentocv** [comment]
Can you upload a image capture of that?
