### ISSUE TITLE
Unregular reset of all room association

### ISSUE THREAD

**Issue by reziCCAA** [colinbendell/homebridge-blink-for-home#24]
Since I have installed this plug-in, all devices running on t this Homebridge server get unregularly removed from the associated room and appear in the standard room. 
Also all automations are deleted.

**Comment by colinbendell** [comment]
I have found this happens when homebridge's cache gets corrupt. can you check the logs and see what errors might be present?

**Comment by reziCCAA** [comment]
I have an eye on that. 
Had the same effect after deinstalling the blink plug-in. There I recognised, that only the Hue devices were wrongly arranged. Maybe it's a coincidence.
Keep you informed.

**Comment by colinbendell** [comment]
can you confirm which version of homebridge you are running?

I'd also check your if you are using an SSD card - might be early signs of wear. Closing for now since

**Comment by reziCCAA** [comment]
All software is up to date. The card is three months old and of a good brand. Hope that is not the issue behind...

After reinstalling your recent update all is working now for three days. 

So, all is fine again. Thanks for prompt answers!
