### ISSUE TITLE
Timing of blink motion sensor and automations with Homekit

### ISSUE THREAD

**Issue by vdrover** [colinbendell/homebridge-blink-for-home#28]
I have been testing triggering lighting using the Blink motion sensor. It works fine, but there is about a 30-second delay between motion sensing and the homekit automation. 

When i use the same automation with a separate motion sensor (Eve Motion), the lights come on within 1-2 seconds of motion detection. 

Anyone else had similar experiences?

**Comment by colinbendell** [comment]
Yea. This is a problem with the APIs. Blink only updates the timestamps on the APIs after the recording is completed. If you have it set to 20s recordings on motion, then the API is only updated after that 20s. However, the Blink For Home polls the server every 20s as well. So in this case it could take up to 40s in worst case scenario, or 20s in the best case scenario to recognize there is motion. 

There does look like an option is being explored for 'early alerts', but I don't have any insight into how this is going to be exposed in the Blink API.

**Comment by vdrover** [comment]
Colin, you are awesome! Great explanation that matches my testing. I had already decided to get a few Eve Motion sensors to pair with blink.
