### ISSUE TITLE
Cant change motion detect

### ISSUE THREAD

**Issue by andre678** [colinbendell/homebridge-blink-for-home#30]
Can't control mini blink camera motion detection from homebridge / apple home, but I can do so from the blink Iphone  app.

 Every time I try and turn the mini motion detect **on** from within Home, it  shows ON in Home  for a few seconds, and then OFF  again.

[22/11/2020, 15:18:06] [Blink] Enabled for Blink mini is: true
[22/11/2020, 15:18:14] [Blink] Enabled for Blink mini is: false

If I  turn if **off** using Home, it shows OFF for a few seconds in HOME and then ON again.

[22/11/2020, 15:26:58] [Blink] Enabled for Blink mini is: false
[22/11/2020, 15:27:00] [Blink] Enabled for Blink mini is: true

I wonder if this is specific to the Mini?

**Comment by colinbendell** [comment]
I've overhauled a bunch of the logic under the hood for this. can you confirm to see how this behaves in v3.7?

**Comment by mccabemj** [comment]
@colinbendell this is still happening for me on v3.7.1. 

It enables, then auto disables. If I enable on the blink app it stays enabled. 

This is also only happening for me on the Blink Mini. I have the original blink, and the new outdoor blink on the same sync module and they are working as expected

**Comment by mccabemj** [comment]
@colinbendell I have looked into the source code. I noticed this

https://github.com/colinbendell/homebridge-blink-for-home/blob/d74586a49db2bf2ef0370d137c3d596c6d6e1ca9/src/blink.js#L505

Can you remember the reason for that comment? Could be an explanation. 

This integration is very important to my Automation flow so would like to get this fixed if possible. More than happy to help if I can

**Comment by colinbendell** [comment]
Yea, I don't have mini hardware so I don't have any insight into the operation of the API.

If you are able to set up a proxy on your local device (eg: using mitmproxy) and record the  API calls to and from, I could would be able to fix this flow. I would just need to record the app enabling and then disabling the camera for motion.

**Comment by mccabemj** [comment]
@colinbendell inspected the traffic and found the issue. Have posted a PR for it if you can take a look please
