### ISSUE TITLE
Temperature does not work below 0

### ISSUE THREAD

**Issue by stijndevries** [colinbendell/homebridge-blink-for-home#32]
Hi, first of thank you for this fantastic plugin! 

I haven't been able to properly debug it yet (it has only gone below 0 once) but it appears like the temperature for my blink doesn't work if its less than 0. The temperature (the camera showed up fine) showed up in the Home app as No Response while my other Blink cameras (above 0) worked fine. In the home bridge logs the temperature did show up properly:
`[30/11/2020, 01:21:18] [Blink] Temperature for Blink Garden is: -3.3`
The temperature also showed up properly in the Blink app.

It stopped working just when the temperature went below 0 and just started working again as it got above 0. This all is in °C. I will take a look if this happens again and also shows up wrong in other HomeKit apps.

**Comment by magaHH** [comment]
See and maybe try my pull request

**Comment by colinbendell** [comment]
Thanks! I've been buried in other personal matters and hope to spend time
catching up and fixing these bugs tonight and tomorrow.

**Comment by colinbendell** [comment]
fixed in v3.7.0
