### ISSUE TITLE
RTSP streaming not working on phone/Mac

### ISSUE THREAD

**Issue by yaxing** [colinbendell/homebridge-blink-for-home#35]
Hi, I'm on version `v3.6.2` and live streaming is not working on iPhone or Mac Home App, but works fine on Apple Watch.

```
LiveView Stream: rtsps://lv1-app-prod.immedia-semi.com:443...
```

Any idea what's wrong?

**Comment by yaxing** [comment]
Noticed a thread describing similar symptom: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/248

Could it be sth in the `ffmpeg-for-homebridge` lib you're using? I also observe same behavior on other plugins using same lib.

**Comment by hunterpaul** [comment]
Same issue for me. When I attempt to view the live stream I get a no response message and the CPU on my RPi which is running Homebridge maxes out. Requires a restart to get it back to normal levels.

**Comment by hunterpaul** [comment]
Also, it seems that it tries to keep the live stream open which sapped a load of power from the cameras batteries

**Comment by colinbendell** [comment]
I've overhauled the livestream comand handling to ensure hte live view is closed down as soon as possible. can you verify?

**Comment by hunterpaul** [comment]
Working well for me now. Thank you!

**Comment by yaxing** [comment]
It’s working for me as well, thank you!
