### ISSUE TITLE
Feature Request: Disable Alarm 

### ISSUE THREAD

**Issue by donavanbecker** [colinbendell/homebridge-blink-for-home#36]
Is it possible to disable the alarm piece of the plugin? so that it isn't displayed in Homekit? 

it would be nice if there was an option in the config, so you can choose to display It or not.

**Comment by donavanbecker** [comment]
#37 fixes this.

**Comment by colinbendell** [comment]
This is integrated in v3.7. Can you clarify why you don't want the security system part of the homebridge setup? Is it just the alarming you don't want (and instead rely only on the motion detection?) What is your typical workflow?

**Comment by donavanbecker** [comment]
@colinbendell yeah I just wanted the feature of having the camera motion integrated since I only have a camera. so having an options of just having the camera, motion and temp.
