### ISSUE TITLE
Blink Won't Arm/Disarm

### ISSUE THREAD

**Issue by rcoletti116** [colinbendell/homebridge-blink-for-home#4]
My cameras are XT2 and the new Indoor/Outdoor. It seems as though the actions of the plugin do not properly reflect to the system or app for me.

Arming in HomeKit does not arm in Blink. In fact, it seems as though the operation may be timing out as HK switches to "arming" but never to "armed," eventually resetting.

Logs & debug don't indicate anything specifically about these actions other than "target state."

[10/25/2020, 12:12:12] [Blink] Armed (Target) for Blink Beta3 is: 1

Also the Occupied switch reverts its own after short periods of time.
[10/25/2020, 11:20:17] [Blink] Occupied Mode for Blink oaklake is: false
[10/25/2020, 11:20:29] [Blink] Occupied Mode for Blink oaklake is: true

**Comment by crowston** [comment]
The plugin successfully authenticates and lists the cameras. It does seem to be working to turn motion detection on/off for specific cameras, which is a helpful feature. 

However, I also don't think it's working to arm or disarm the whole system, though I'm not certain I understand how the home/away/off switch and the occupied switch settings interact or in fact what the later switch is for. When I operate the switches in the Home app, I see log messages like "Occupied Mode for Blink Home is: false" or "Armed (Target) for Blink Home is: 1" but unlike turning motion detection on/off, I don't see a URL that's being accessed. 

Also, the thumbnail always says Privacy mode, regardless of what the privacy switch on the camera is set to (again, maybe I'm not sure what the switch is supposed to do). Viewing the camera shows a test pattern and that persists for a few seconds after closing the live stream, but then swtches back to the privacy mode image. 

But the progress seems very encouraging, so thanks for pushing things this far!

**Comment by colinbendell** [comment]
Also overhauled the arm and disarm logic. I'm waffling again on the distinction between HOME/AWAY/DISARM and what this should mean for the accessory. I think my current assumptions are wrong and that perhaps HOME should == armed but not set off the security system? (and just update the thumbnail and trigger the motion sensor?)

Feedback is welcome.

**Comment by crowston** [comment]
The new version does seem to be arming/disarming individual cameras and the system as a whole. I can change the status in the Home app and it updates in the Blink app.

**Comment by colinbendell** [comment]
thanks!
