### ISSUE TITLE
Error: "The session has been destroyed"

### ISSUE THREAD

**Issue by leny** [colinbendell/homebridge-blink-for-home#43]
Hello, thanks for this great plugin!

I'm using it for 2 days and it's working well, until, at night, I got this error:

```
[12/01/2021, 02:02:09] [Blink] Error: read ETIMEDOUT
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'read'
}
(node:21187) UnhandledPromiseRejectionWarning: Error: read ETIMEDOUT
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:21187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/01/2021, 07:24:44] [Blink] Refreshing snapshot for Blink Salon
[12/01/2021, 07:24:44] [Blink] Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed
    at ClientHttp2Session.request (internal/http2/core.js:1606:13)
    at doFetch (/usr/local/lib/node_modules/homebridge-blink-for-home/node_modules/fetch-h2/dist/lib/fetch-http2.js:51:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_HTTP2_INVALID_SESSION'
}
Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed
    at ClientHttp2Session.request (internal/http2/core.js:1606:13)
    at doFetch (/usr/local/lib/node_modules/homebridge-blink-for-home/node_modules/fetch-h2/dist/lib/fetch-http2.js:51:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_HTTP2_INVALID_SESSION'
}
```

It seems that some network errors are not catched - then makes the plugin to crash.
A restart of homebridge fixes the issue, but the whole point of the stuff is to _not_ having to reboot it every morning.

I will try to take a look at the code, but if you can point me in the right direction, it would be useful.

Thanks again,

**Comment by leny** [comment]
Small update: when the privacy mode is **enabled**, I don't have the issue.

**Comment by reziCCAA** [comment]
I have the same problem.

**Comment by gdotp01** [comment]
I get this occasionally and it seems to stop some , but not all, homebridge plugins working until I restart homebridge. I synchronise this and my ring alarm and when blink fails with this error the ring alarm also seems to be failing without any effort messages in the log.

**Comment by magaHH** [comment]
I updated node.js from 12.18.2 to 14.15.4 and this issue seems to be gone...

**Comment by leny** [comment]
I'm already on node `14.15.1`, will try the `14.15.4`…

**Comment by gdotp01** [comment]
![4CF262BD-7257-4924-BA27-18703FF8E049](https://user-images.githubusercontent.com/50060482/106247930-267e3d80-6208-11eb-85e0-b5f0dea05c2d.png)
![0F444CB0-58C7-41C1-AE9C-71EE8B3D2315](https://user-images.githubusercontent.com/50060482/106247935-28480100-6208-11eb-85f6-9bfd8de1c997.png)
![5D48DD08-F4F7-43DC-9695-12EBDEDF75E1](https://user-images.githubusercontent.com/50060482/106247937-28e09780-6208-11eb-9761-851fcdf2cc0c.png)


This happened again last night. Most plugins continued to work but the ring one failed as well.

**Comment by hunterpaul** [comment]
Same issue for me too. Having to restart Homebridge to rectify the problem on a regular basis. When it happens, my Blink automations fail

**Comment by xImportExportx** [comment]
I am having the same issue too just to add. I’m running the docker container version of homebridge. Any ideas what the underlying issue is?

**Comment by gdotp01** [comment]
I’m getting round this until it’s fixed by using the IFTTT service to turn them off. It only seems to be the turn off that causes the issue.

**Comment by colinbendell** [comment]
This uses a long running TLS socket which appears to trigger out of hand socket handling. I've added some additional network handling and I'll see if I can capture these ephemeral SESSION hangups on the h2 stream. stay tuned.

**Comment by cristian5th** [comment]
> I’m getting round this until it’s fixed by using the IFTTT service to turn them off. It only seems to be the turn off that causes the issue.

Me too, I'm only getting the issue during the turn off request. Automations for turning on are working.

**Comment by hunterpaul** [comment]
Confirming that the new version is working fine for me. No longer seeing this problem and my automations are working great. Thank you

**Comment by colinbendell** [comment]
great!
