### ISSUE TITLE
Just got this email today from Blink (question)

### ISSUE THREAD

**Issue by mtressl** [colinbendell/homebridge-blink-for-home#47]
Any idea if this will have an impact on the plugin?

**Update: SMS Two-Step Verification**
_Your privacy and security is important to us. For added account security, we have released 2-Step Verification (2SV) support using text message or phone call issued verification codes with the latest Blink Home Monitor app versions (Android 6.2.6 and iOS 6.1.5). To take advantage of this feature, enter a valid phone number under Manage Account in your Blink Home Monitor app. In the coming weeks, Blink customers will be prompted to set up 2SV using a valid phone number._

**Comment by tombenton55** [comment]
Was just about to post about this, doesn’t seem like it should be an issue. But as with everything blink do, it will probably break something.

**Comment by colinbendell** [comment]
Just added the necessary fix for it. It's mostly transparent, but they did accompany this with a v5 api bump for auth.

**Comment by mtressl** [comment]
Great, thanks @colinbendell for the necessary fix.
Highly appreciated!

**Comment by magaHH** [comment]
Thank you very much for the updates Colin. Do you mind publishing it to npmjs as well so it is easies to update. thx!!

**Comment by colinbendell** [comment]
This is included in v3.7
