### ISSUE TITLE
ffmpeg processes left running

### ISSUE THREAD

**Issue by crowston** [colinbendell/homebridge-blink-for-home#5]
I noticed this morning that three ffmpeg processes were left running. Sorry, I don't have any details about how that happened.  That was with version 3.5.5 though, so maybe no longer a problem.

**Comment by colinbendell** [comment]
yea. I just put the stock homebridge video accessory in place and it appears to go rogue. I've noticed this behavior myself and hoping that once I get back to liveview implementation I'll clean that up too.

**Comment by vdrover** [comment]
Is this related perhaps? I see a preview of the camera as expected:
![image](https://user-images.githubusercontent.com/3143313/97688584-4fa3fc00-1a68-11eb-91b4-260b261421c3.png)
But if i click on the thumbnail, i get this:
![image](https://user-images.githubusercontent.com/3143313/97688624-60ed0880-1a68-11eb-96ef-c97d7eb18216.png)

**Comment by colinbendell** [comment]
no, the preview is a thumbnail (jpg) that uses different apis. It's the
live camera delegate that is spawning and not tracking the ffmpeg process.
The code that's in there is completely temporary

**Comment by vdrover** [comment]
Understood. Happy to test subsequent versions.

**Comment by colinbendell** [comment]
liveview is still not ready, but I think the zombie ffmpeg bug is at least fixed in the interim.

**Comment by crowston** [comment]
Thanks for the update. A minor glitch: I have the privacy switch hidden, but am getting the privacy mode image for two of the cameras, which maybe not coincidentally are the ones that aren't armed. I am seeing the preview for one camera, which is also one that's armed.

**Comment by colinbendell** [comment]
not sure it properly worked in the first place. now fixed. live view now works as well

**Comment by crowston** [comment]
I just tried it out and wow, works great! Thanks for your efforts!

**Comment by ratsoid** [comment]
oh wow @colinbendell 
do you by any chance have a paypal account? I would really love to buy you a couple of beers

**Comment by vdrover** [comment]
Live view working well it seems for v3.5.13. Previews on the `Home` page of the `Home` app working well also, including thumbnail updates.

**Comment by NiallBellxD** [comment]
First off, excellent work on this Plugin Colin, it's great!

I just wanted to drop a message on here to say that each time a camera is clicked in the home app, an ffmpeg process is launched on my mac mini & it thrashes the CPU. Is there a way to have these processes kill themselves?

Cheers!

2014 MPB (macOS Catalina)
Homebridge v1.1.7
Blink Plugin v3.6.2

**Comment by colinbendell** [comment]
I've overhauled some of the ffmpeg logic. more needs to be done. but it should address all the major issues with ffmpeg running for long periods of time.
