### ISSUE TITLE
Multiple System Support?

### ISSUE THREAD

**Issue by MasterofKungfu9999** [colinbendell/homebridge-blink-for-home#59]
Hi,

Can you tell me if blink for home supports multiple systems of Blink?

Thanks

**Comment by mccabemj** [comment]
@MasterofKungfu9999 do you mean multiple homes? I.e multiple hubs? If so then yes, I have it working with two

**Comment by colinbendell** [comment]
Yes it does. Each system will show up with a separate 'security system' to arm all cameras on that system.
