### ISSUE TITLE
Thumbnails refreshing for 1 system but not 2nd

### ISSUE THREAD

**Issue by shawnyboy66** [colinbendell/homebridge-blink-for-home#6]
I have 2 blink systems set up in my home (an outdoor one that is armed 24/7, and an indoor one which arms when the last person leaves and disarms when the first person comes home). I was doing the arming and disarming through IFTTT until today when I set up HOOBS with your blink module. 

I know you said live view is a WIP but the thumbnail refreshes seem to be off for me. 
My outdoor system works like a charm and updates the thumbnails every so often. My indoor system is still using the stock images that I initially saved in the Blink app. and will not refresh. I have attached a picture of my settings through HOOB.
![Screen Shot 2020-10-26 at 2 42 20 PM](https://user-images.githubusercontent.com/73497497/97220562-a9bb6d80-1799-11eb-86e4-2cc26db8ca8c.png)

any idea what the issue could be?

**Comment by shawnyboy66** [comment]
I would also like to say... THANK YOU! I have been looking for a home bridge plugin for Blink for years, and this is freaking awesome. I have pretty much every blink camera (mini, indoor, outdoor XT1, XT2, the new indoor) so if you need help testing functionality of this, I am onboard.

**Comment by colinbendell** [comment]
can you confirm which version of the plugin you are using? Can you provide me any console logs you have? Feel free to DM me (twitter, discord) the details. If you are comfortable, turning on debug and providing me the api call outputs would also be useful.

**Comment by shawnyboy66** [comment]
Dmd you on twitter and emailed the HOOBS log

**Comment by colinbendell** [comment]
should be resolved now.
